blog/backend/accounts/urls.py
from django.urls import path

from .views import SignUpView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

blog/backend/config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.http import HttpResponseRedirect
from django.urls import include, path


def redirect_to_posts(request):
    return HttpResponseRedirect("posts/")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", redirect_to_posts),
    path("posts/", include("posts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),

    path("api/", include("posts.api_urls")),
    # path("accounts/", include('accounts.urls')),
    # path("authentication/", include('authentication.urls')),
    # path("another_app/", include('another_app.urls'))
]

urlpatterns += staticfiles_urlpatterns()

blog/backend/posts/urls.py
from django.urls import path

from posts.views import (PostCreateView, PostDeleteView, PostDetailView,
                         PostsListView, PostUpdateView)

# We use this for namespaces in urls in templates
app_name = "posts"

urlpatterns = [
    path("", PostsListView.as_view(), name="list"),
    path("<int:pk>/", PostDetailView.as_view(), name="detail"),
    path("new/", PostCreateView.as_view(), name="create"),
    path("update/<int:pk>/", PostUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", PostDeleteView.as_view(), name="delete"),
]

blog/backend/accounts/models.py
from django.db import models

# Create your models here.

blog/backend/posts/models.py
"""
Post:
id: int +
title: str
content: str
author_id: int

User:
id: int
username: str
first_name: str
last_name: str
password: str
"""
from django.conf import settings
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="posts", on_delete=models.CASCADE
    )

    # If we don't wanna use real delete from the database. Look into the view.py PostsListView
    # deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    # def save(self, author):
    #     self.author = author
    #     instance = self.save()
    #     return super().save()


# me = User.objects.get(id=3)
# me.posts.all() <== Queryset()

# Post.objects.all() <== Queryset()
# Post.objects.first() <== Model
# Post.objects.last()
# Post.objects.create(author=admin, title='asdasd')
# Post.objects.update()
# post = Post.objects.get(author_id=3)
# result = Post.objects.filter(title="VIM")

# Что такое result ?
# result -> QuerySet() == list[dict,]
# post = Post.objects.first()

# results = [{}, {}, {}]
# post = results[2]
# post = {
# 	"id": 1,
# 	"title": "VIM"
# 	"content": "How to learn VIM",
# 	"author_id": 3
# }

# post["title"] ==> post.id / post.content
# ======================
# post = Post.objects.get(title="VIM")
# ??? post.author.username ???
# author = User.objects.get(id=post.author_id)
# author.username !!!!!!

blog/backend/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


# The example why we are using built in django classes
# class SignUpForm(forms.ModelForm):
#     re_password = forms.CharField()

#     class Meta:
#         model = User
#         # fields = ["username", "password1", "password2"]
#         fields = ["username", "password", "re_password"]

#     def clean(self):
#         if self.data['password'] != self.data['re_password']:
#             raise ValueError("Passwords are not match")

#         import ipdb; ipdb.set_trace(context=10)


#     def save():
#         ...


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
        ]

blog/backend/posts/forms.py
from django.contrib.auth import get_user_model
from django import forms

from .models import Post

User = get_user_model()


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]

    # def save(self, author: User):
    #     self.instance.author = author
    #     self.instance.save()
    #     return self.instance

blog/backend/accounts/views.py
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SignUpForm

User = get_user_model()


class SignUpView(CreateView):
    model = User
    form_class = SignUpForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

blog/backend/posts/views.py
# from django.http import HttpRequest, HttpResponse
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import PostCreateForm
from .models import Post

User = get_user_model()


# def posts(request: HttpRequest) -> HttpResponse:
#     qs = Post.objects.all()
#     post_titles = [post.title for post in qs]
#
#     content = f"""<h1>Posts: {post_titles}</h1>"""
#
#     return HttpResponse(content)


class PostsListView(ListView):
    model = Post
    template_name = "posts/index.html"
    authentication_classes = []

    def get(self, request):
        return super().get(request)

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data(object_list=object_list, **kwargs)
        ctx["foo"] = 12

        return ctx

    def get_queryset(self):
        # See in the model.
        # return Post.objects.filter(deleted=False)
        if isinstance(self.request.user, User):
            return Post.objects.filter(author=self.request.user)
        return None


class PostDetailView(DetailView):
    model = Post
    template_name = "posts/detail.html"
    context_object_name = "my_post"


class PostCreateView(CreateView):
    model = Post
    form_class = PostCreateForm
    success_url = reverse_lazy("posts:list")
    template_name = "posts/create.html"
    # fields = ["title", "content"] # Uses only with model (not with form_class)

    # def post(self, request):
    #     user = request.user

    #     return super().post(request)

    # def form_valid(self, form):
    #     self.object = form.save(author=self.request.user)
    #     return super().form_valid(form)

    # Better approach in the forms.py file
    def post(self, request):
        data = dict(request.POST)
        form = PostCreateForm(data)
        if form.is_valid():
            form.cleaned_data["author"] = request.user
            Post.objects.create(**form.cleaned_data)

        return HttpResponseRedirect(reverse_lazy("posts:list"))


class PostUpdateView(UpdateView):
    model = Post
    success_url = reverse_lazy("posts:list")
    template_name = "posts/update.html"
    fields = ["title", "content"]


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy("posts:list")
    template_name = "posts/delete.html"

    # Use if we don't wanna use real delete from the database. Look into the models.py :: Post
    # def delete(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     success_url = self.get_success_url()
    #     self.object.deleted = True
    #     self.object.save()

    #     return HttpResponseRedirect(success_url)

blog/backend/templates/accounts/signup.html
{% extends 'base.html' %}


{% block additional %}
<h1>Nothing to show</h1>
{% endblock additional %}


{% block content %}
User signup
</br>

<form action='' method='post'>{% csrf_token %}
    {{ form }}
    <input type='submit' value='User registration'>
</form>

{% endblock content %}

blog/backend/templates/base.html
{% load static %}

<html>
<head>
    <title>SkillUp blog</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
    <div class="header">
        Header
    </div>

    <!-- <div class="body" style="background-color: red;"> -->

    {% if user.is_authenticated %}
        <div class="body">
            {% block content %} {% endblock content %}
        </div>
    {% else %}
        <div class="body">
            {% block notauth_content %} {% endblock notauth_content %}
        </div>
    {% endif %}


    <div class="divider">
        <p>=====================</p>
    </div>
    
    <div class="additional_data">
        {% block additional %} {% endblock additional %}
    </div>

    <div class="footer">Footer</div>
</body>
</html>

blog/backend/templates/posts/create.html
{% extends 'base.html' %}


{% block additional %}
<h1>Nothing to show</h1>
{% endblock additional %}


{% block content %}
Post creation -----
</br>

<form action='' method='post'>{% csrf_token %}
    {{ form }}
    <input type='submit' value='Create new post'>
</form>

{% endblock content %}

blog/backend/templates/posts/delete.html
{% extends 'base.html' %}


{% block additional %}
<h1>Nothing to show</h1>
{% endblock additional %}


{% block content %}
Post delete -----
</br>

<form action='' method='post'>{% csrf_token %}
    <p>Are you sure that you wanna delete post {{ post.title }}</p>
    <input type='submit' value='Yes!'>
</form>

{% endblock content %}

blog/backend/templates/posts/detail.html
{% extends 'base.html' %}


{% block additional %}
<h1>Nothing to show</h1>
{% endblock additional %}


{% block content %}
Post: -------
<p><a href="{% url 'posts:update' my_post.pk%}">Update this post</a></p>
<p><a href="{% url 'posts:delete' my_post.pk%}">Delete this post</a></p>

<h1>Header: {{ my_post.title }}</h1>
<h1>Content:</h1>{{ my_post.content }}
<h1>Author: {{ my_post.author }}</h1>


{% endblock content %}

blog/backend/templates/posts/index.html
{% extends 'base.html' %}




{% block additional %}
<h1>Hello</h1>
{% endblock additional %}

{% block notauth_content %}
    User is not authorized, please login
	<p><a href="{% url 'login' %}">Login</a></p>
	<p><a href="{% url 'accounts:signup' %}">SignUp</a></p>
{% endblock notauth_content %}

{% block content %}
	<p><a href="{% url 'logout' %}">Logout</a></p>
    Posts:

    <a href="{% url 'posts:create' %}">Create new post</a>

    <ul>
        {% for post in object_list %}
            <li>
                <div class="">
                    <a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
                </div>
            </li>
        {% endfor %}
    </ul>

{% endblock content %}

blog/backend/templates/posts/update.html
{% extends 'base.html' %}


{% block additional %}
<h1>Nothing to show</h1>
{% endblock additional %}


{% block content %}
Post update -----
</br>

<form action='' method='post'>{% csrf_token %}
    {{ form }}
    <input type='submit' value='Update post'>
</form>

{% endblock content %}